In [1]:
import numpy as np
from module3 import and_gate, nand_gate, nor_gate, or_gate, xor_gate

# numpy array of all four input combinations for the logic gates
# [0, 0]
# [0, 1] 
# [1, 0] 
# [1, 1]
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# AND Gate

In [2]:
# loop through the input array and compute the outputs for the AND gate and save them in an array
and_results = np.array([and_gate.compute(row) for row in inputs])

print("AND Gate Results:")
print(and_results)

AND Gate Results:
[0 0 0 1]


# NAND Gate

In [3]:
# loop through the input array and compute the outputs for the NAND gate and save them in an array
nand_results = np.array([nand_gate.compute(row) for row in inputs])

print("NAND Gate Results:")
print(nand_results)

NAND Gate Results:
[1 1 1 0]


# OR Gate

In [4]:
# loop through the input array and compute the outputs for the OR gate and save them in an array
or_results = np.array([or_gate.compute(row) for row in inputs])

print("OR Gate Results:")
print(or_results)

OR Gate Results:
[0 1 1 1]


# NOR Gate

In [5]:
# loop through the input array and compute the outputs for the NOR gate and save them in an array
nor_results = np.array([nor_gate.compute(row) for row in inputs])

print("NOR Gate Results:")
print(nor_results)

NOR Gate Results:
[1 0 0 0]


# XOR Gate

In [6]:
# loop through the input array and compute the outputs for the XOR gate and save them in an array
xor_results = np.array([xor_gate.compute(row) for row in inputs])

print("XOR Gate Results:")
print(xor_results)

XOR Gate Results:
[0 1 1 0]
